server:
  port: 8080 # 서버 포트 번호


logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc9th?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 1234


  jpa:
    hibernate:
      # ddl-auto 옵션:
      # create: 서버 시작 시 기존 테이블 삭제 후 새로 생성
      # update: 변경된 스키마만 찾아서 반영
      # validate: Entity와 테이블이 정상 매핑되었는지 검증만 함
      # none: 사용 안 함 (운영 환경에서 권장)
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 보기 좋게 포맷팅하여 로그에 출력
    show-sql: true # 실행되는 SQL 쿼리를 로그에 출력
